dubbo:
  application:
    name: provider-service
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
#    port: 20880
  scan:
    base-packages: cn.accp.service.impl
spring:
  application:
    name: mydubbo-provider
  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: ok
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full # resultMap 自动配置 容易出错